repos:
- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  - id: detect-secrets
    args: ["--baseline", ".secrets.baseline"]

- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
  - id: bandit
    args: ["-c", "pyproject.toml"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.11.6
  hooks:
  - id: ruff
    args: ["--config=pyproject.toml"]
  - id: ruff-format
    args: ["--config=pyproject.toml"]

- repo: https://github.com/commitizen-tools/commitizen
  rev: v4.6.0
  hooks:
    - id: commitizen
