version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: mock-rest-server
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=8000
      - SERVER_RELOAD=false
      - SERVER_WORKERS=4
      - DB_TYPE=sqlite3
      - "DB_HOST=sqlite+aiosqlite:///:memory:"
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
